Add pages
Timowest12/capstone pull request #1
Opened 2021-10-11 21:07 UTC by Timowest12

Created the template and personalised it by making it for a fictional chess tournament.

2021-10-13 16:31 UTC, dasileker requested changes
### **Hi @Timowest12,** 

### **To Highlight**

- The **PR** is good.
- The commit is good.

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-13 16:31 UTC, dasileker commented on about.html
> +    </style>
- [ ] Please add the style in the CSS file.

2021-10-13 16:31 UTC, dasileker commented on about.html
> +    </nav>
- [ ] The mobile menu is not working you should also work here.

2021-10-13 16:31 UTC, dasileker commented on index.html
> +    </style>
- [ ] Same rule please add this in the CSS file

2021-10-13 16:31 UTC, dasileker commented on index.html
> +      </nav>
- [ ] I do see something on the left of the mobile menu, please correct it. and also the display center for the links are a bit deviated.

![Inkedmob](https://user-images.githubusercontent.com/61562626/137174062-8afd2ef8-01f1-460a-8c6c-9187a51e9cd5.jpg)

2021-10-13 16:31 UTC, dasileker commented on index.html
> +     </div>
- [ ] The view for the partner is too big in the mobile view, please correct it.

![mob-foot](https://user-images.githubusercontent.com/61562626/137174301-449bd448-14b9-48aa-846d-f0e3a4064f0c.jpeg)

2021-10-13 16:31 UTC, dasileker commented on index.html
> +                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Reprehenderit, atque itaque, aliquid corrupti ducimus pariatur ipsa sunt alias repudiandae laudantium accusantium dolorum
- [ ] The footer has a margin too big and also the color is different from the design.

- **Original footer design**
![roig](https://user-images.githubusercontent.com/61562626/137174746-316c7120-eaf4-45fa-a3c2-e79c18e1d39d.jpeg)


- **Your design**

![mqmlq](https://user-images.githubusercontent.com/61562626/137174791-472c04bc-a734-49dd-8cad-8808cb145242.jpeg)

2021-10-13 16:31 UTC, dasileker commented on README.md
> +After downloading you can directly open the index.html file in any kind of text editor to make adjustments. Or open in a web browser to view your new site.
- [ ] This part `getting started` should contain details to the non-technical person on how they should proceed, like go to then do.

2021-10-14 09:39 UTC, Mihndim2020 requested changes
## Hi @Timowest12, 

Great work on making the changes requested by a previous reviewer 👏 👏 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
![stay-strong-youre-almost-there](https://user-images.githubusercontent.com/65852621/133678845-1b015b27-e9bc-4784-a316-bc699db8237a.jpg)


 # Status: Requires Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Please also consider:
- [OPTIONAL] The mobile version of your app is not well centralized, please kindly fix that. See image below. 
![tim4](https://user-images.githubusercontent.com/65852621/137292403-e9b39f9e-8f5e-4cfe-8a4f-84706a8f4156.png)

![tim5](https://user-images.githubusercontent.com/65852621/137292422-1139d29c-7140-4d96-b268-51fa6b69bf67.png)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-14 09:39 UTC, Mihndim2020 commented on about.html
> +    <nav id="secnavbar" class="secnavbar">
- [ ] As requested by the former code reviewer, which also a requirement for this project, please make sure you can switch between the home and about page in you mobile view. 
- [OPTIONAL ] Please kindly make sure your mobile view is centralized, the footer is also absent for the mobile view, please kindly fix that.  see image below.  
![TIMO01](https://user-images.githubusercontent.com/65852621/137288486-737c6288-a51f-4b8d-99a7-68213b95a338.png)
 
![TIMO02](https://user-images.githubusercontent.com/65852621/137288527-43deaed4-9c4c-4569-9c43-26d79ff15a5d.png)

2021-10-14 09:39 UTC, Mihndim2020 commented on index.html
> +                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Reprehenderit, atque itaque, aliquid corrupti ducimus pariatur ipsa sunt alias repudiandae laudantium accusantium dolorum
- [ ] As requested by the former code review please sure this footer is implemented as in the design. Also take a look at the mobile view footer.
![timo03](https://user-images.githubusercontent.com/65852621/137291452-fc00a5e4-0158-432e-bc8f-b0c2f25f5432.png)

2021-10-14 09:39 UTC, Mihndim2020 commented on index.html
> +     </div>
- [ ] Please kindly fix your mobile footer as requested by the former reviewer, see image below.

2021-10-14 11:28 UTC, Lameck1 commented on index.html
> +     </div>
Fixed. Too much content in the footer makes it not look good in the mobile view. Consider reducing the words, since it is just some lorem ipsum.

2021-10-14 11:29 UTC, Lameck1 commented on index.html
> +                <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Reprehenderit, atque itaque, aliquid corrupti ducimus pariatur ipsa sunt alias repudiandae laudantium accusantium dolorum
Fixed but could be improved

2021-10-14 11:29 UTC, Lameck1 commented on about.html
> +    <nav id="secnavbar" class="secnavbar">
Well implemented 👍🏼

2021-10-14 11:36 UTC, Lameck1 approved these changes
Hi, @Timowest12,

Well done 👏🏼. You've put in so much effort in building this project and working on the requested changes by previous reviewers. 

Your project is now complete!  You may merge this branch :shipit: 

Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-10-14 11:36 UTC, Lameck1 commented on styles/styles.css
> +  display: flex;
- [ ] [OPTIONAL] Let's strive to keep the code DRY. This property:
```CSS
display: flex
```
has been used around 20 times in the CSS. Please refactor it to a class and apply the class in the HTML file to elements that share the same display property.

### Example code
```CSS
.d-flex {
  display: flex;
  align-items: center;
}
```

Then apply this class to HTML element that needs this behavior:

```HTML
  <section class="d-flex">
```

2021-10-14 11:37 UTC, merged